version: '3.1'

services:

  mongo:
    image: mongo:7-jammy
    restart: unless-stopped
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
    volumes:
      - type: bind
        source: ./js.d
        target: /docker-entrypoint-initdb.d
        read_only: true

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASS}"
      ME_CONFIG_MONGODB_SERVER: "mongo"
      #ME_CONFIG_BASICAUTH_USERNAME: "${MONGOEXPRESS_USER}"
      #ME_CONFIG_BASICAUTH_PASSWORD: "${MONGOEXPRESS_PASS}"